2025-02-14 14:56:22,917 INFO    MainThread:3411353 [wandb_setup.py:_flush():76] Current SDK version is 0.17.3
2025-02-14 14:56:22,917 INFO    MainThread:3411353 [wandb_setup.py:_flush():76] Configure stats pid to 3411353
2025-02-14 14:56:22,917 INFO    MainThread:3411353 [wandb_setup.py:_flush():76] Loading settings from /n/home00/sumedh/.config/wandb/settings
2025-02-14 14:56:22,917 INFO    MainThread:3411353 [wandb_setup.py:_flush():76] Loading settings from /n/home00/sumedh/spmax_sae/experiments/expt16_intrindicdimX/wandb/settings
2025-02-14 14:56:22,917 INFO    MainThread:3411353 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2025-02-14 14:56:22,917 INFO    MainThread:3411353 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2025-02-14 14:56:22,917 INFO    MainThread:3411353 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'experiments/expt16_intrindicdimX/trainmodel.py', 'program_abspath': '/n/home00/sumedh/spmax_sae/experiments/expt16_intrindicdimX/trainmodel.py', 'program': '/n/home00/sumedh/spmax_sae/experiments/expt16_intrindicdimX/trainmodel.py'}
2025-02-14 14:56:22,917 INFO    MainThread:3411353 [wandb_setup.py:_flush():76] Applying login settings: {}
2025-02-14 14:56:22,917 INFO    MainThread:3411353 [wandb_init.py:_log_setup():520] Logging user logs to /n/home00/sumedh/spmax_sae/experiments/expt16_intrindicdimX/wandb/run-20250214_145622-zqw8455w/logs/debug.log
2025-02-14 14:56:22,917 INFO    MainThread:3411353 [wandb_init.py:_log_setup():521] Logging internal logs to /n/home00/sumedh/spmax_sae/experiments/expt16_intrindicdimX/wandb/run-20250214_145622-zqw8455w/logs/debug-internal.log
2025-02-14 14:56:22,917 INFO    MainThread:3411353 [wandb_init.py:init():560] calling init triggers
2025-02-14 14:56:22,917 INFO    MainThread:3411353 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {'seed_id': 1, 'device': 'cuda', 'wandbprojectname': 'intrinsic_dimX', 'experiment_date': 'today', 'sae_type': 'relu', 'weight_init': 'random', 'normalize_decoder': True, 'resample_deadneurons': False, 'sae_width': 512, 'kval_topk': 0, 'dataset': '128dgaussian_intrinsicdim', 'num_concepts': 5, 'return_concept_loss': True, 'data_dim': 128, 'save_checkpoints': True, 'batch_size': 2048, 'regularizer': 'l1', 'encoder_reg': True, 'gamma_reg': 20.0, 'optimizer': 'adam', 'clip_grad': True, 'online_training': True}
2025-02-14 14:56:22,917 INFO    MainThread:3411353 [wandb_init.py:init():610] starting backend
2025-02-14 14:56:22,917 INFO    MainThread:3411353 [wandb_init.py:init():614] setting up manager
2025-02-14 14:56:22,940 INFO    MainThread:3411353 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-02-14 14:56:22,964 INFO    MainThread:3411353 [wandb_init.py:init():622] backend started and connected
2025-02-14 14:56:23,008 INFO    MainThread:3411353 [wandb_init.py:init():711] updated telemetry
2025-02-14 14:56:23,324 INFO    MainThread:3411353 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2025-02-14 14:56:23,735 INFO    MainThread:3411353 [wandb_run.py:_on_init():2402] communicating current version
2025-02-14 14:56:23,790 INFO    MainThread:3411353 [wandb_run.py:_on_init():2411] got version response upgrade_message: "wandb version 0.19.6 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2025-02-14 14:56:23,790 INFO    MainThread:3411353 [wandb_init.py:init():795] starting run threads in backend
2025-02-14 14:56:35,061 INFO    MainThread:3411353 [wandb_run.py:_console_start():2380] atexit reg
2025-02-14 14:56:35,064 INFO    MainThread:3411353 [wandb_run.py:_redirect():2235] redirect: wrap_raw
2025-02-14 14:56:35,064 INFO    MainThread:3411353 [wandb_run.py:_redirect():2300] Wrapping output streams.
2025-02-14 14:56:35,064 INFO    MainThread:3411353 [wandb_run.py:_redirect():2325] Redirects installed.
2025-02-14 14:56:35,098 INFO    MainThread:3411353 [wandb_init.py:init():838] run started, returning control to user process
2025-02-14 15:05:09,067 WARNING MsgRouterThr:3411353 [router.py:message_loop():77] message_loop has been closed
